version: '2'
services:
  web:
    build:
      context: .
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTP_PROXYS=${HTTP_PROXY}
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    links:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
